-- Napraw automatyczne generowanie ID dla tabeli profiles

-- Sprawdź, czy potrzebne jest dodanie rozszerzenia uuid-ossp
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Sprawdź typ kolumny id
DO $$
DECLARE
  column_type TEXT;
BEGIN
  -- Pobierz typ kolumny id
  SELECT data_type INTO column_type
  FROM information_schema.columns
  WHERE table_name = 'profiles'
  AND column_name = 'id';

  -- Jeśli kolumna jest typu UUID
  IF column_type = 'uuid' THEN
    -- Ustaw wartość domyślną uuid_generate_v4() dla kolumny id
    ALTER TABLE profiles
    ALTER COLUMN id SET DEFAULT uuid_generate_v4();
  
  -- Jeśli kolumna jest typu INTEGER
  ELSIF column_type = 'integer' OR column_type = 'bigint' THEN
    -- Dodaj generowanie identyfikatora
    BEGIN
      ALTER TABLE profiles
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION WHEN OTHERS THEN
      -- Jeśli już jest identity, ignoruj błąd
      NULL;
    END;
  END IF;
END
$$;

-- Usuń istniejącą kolumnę creation_date jeśli istnieje
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'profiles'
    AND column_name = 'creation_date'
  ) THEN
    ALTER TABLE profiles
    DROP COLUMN creation_date;
  END IF;
END
$$;

-- Dodaj kolumnę created_at jeśli nie istnieje
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'profiles'
    AND column_name = 'created_at'
  ) THEN
    ALTER TABLE profiles
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
  END IF;
END
$$;

-- Usuń wartość NULL z istniejących rekordów
UPDATE profiles
SET id = uuid_generate_v4()
WHERE id IS NULL; 